### ISSUE TITLE
Exception on Java8

### ISSUE THREAD

**Issue by peter-up** [jamius19/paddle-verifier#1]
pSignature = URLDecoder.decode(pSignature, StandardCharsets.UTF_8);  // SecurityUtils.Class
should by 
 pSignature = URLDecoder.decode(pSignature, StandardCharsets.UTF_8.name());

refer: https://stackoverflow.com/questions/6138127/how-to-do-url-decoding-in-java

Could you add support for Java under java 10 and release a new paddle-verifier? Which is really helpfull.

**Comment by jamius19** [comment]
Thank you for opening the issue.
I've been having some problems in my personal life hence the (very!) late reply!
My apologies.

I'll look into it and what do you mean by `Java under java 10`?
Have a good day!

**Comment by peter-up** [comment]
> Thank you for opening the issue.
> I've been having some problems in my personal life hence the (very!) late reply!
> My apologies.
> 
> I'll look into it and what do you mean by `Java under java 10`?
> Have a good day!

Sorry for typo, I mean Java 9 or below.  `URLDecoder.decode(pSignature, StandardCharsets.UTF_8)` is a new feature of Java 10

**Comment by noasic** [comment]
I ran into the same issue on Java 8

**Comment by jamius19** [comment]
Fixed.
See pull req #5 

Closing this issue.
