### ISSUE TITLE
is URL Decoding the signature correct?

### ISSUE THREAD

**Issue by dph01** [jamius19/paddle-verifier#3]
https://github.com/jamius19/paddle-verifier/blob/2f166d6d0e5be2820eb99c9c65af05446c563f88/src/main/java/com/jamiussiam/paddle/verifier/SecurityUtils.java#L55

I'm coming across this for the first time, so apologies if I've got hold of the wrong end of the stick but ...

Are you sure that the you need to URL decode the signature? 

Looking at the other language examples from https://developer.paddle.com/webhook-reference/verifying-webhooks, it appears they only Base64 decode. 

Also the signature that comes through from the Webhook tester https://sandbox-vendors.paddle.com/webhook-alert-test appears not to have url encoded the signature.

**Comment by jamius19** [comment]
Thanks for the input.
I'll check it out.

**Comment by transparentech** [comment]
Yes, the URL decoding is needed. In the referenced example code, the data is already decoded when they do the base64 decoding. This lib is taking a raw request body as input, so it needs to do the URL decoding of every value.
