### ISSUE TITLE
One specific valid paddle webhook is not being verified

### ISSUE THREAD

**Issue by sameerjfreaks** [jamius19/paddle-verifier#8]
I have been using this module in my application for quite some time to verify paddle webhooks.
But today, I observed a problem that one webhook from paddle is constantly denied by this verifier. I couldn't find the problem. It is a completely valid webhook with proper p_signature value.
Can you help me finding the issue?

**Comment by jamius19** [comment]
Hi @sameerjfreaks,
I know it's a bit late, but can you please provide me with a test file like this one [VerifierTest.java](https://github.com/jamius19/paddle-verifier/blob/master/src/test/java/com/jamiussiam/paddle/verifier/VerifierTest.java)  with the data that you're receiving?

**Comment by sameerjfreaks** [comment]
Hello @jamius19,
Thank you for the reply.
I had fixed the issue myself.
I am using Springboot and accessing your project using maven dependency.

In that dependency, there was a mistake in StringParser.class

`package com.jamiussiam.paddle.verifier;

import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.util.Map;

/**
 *
 */
public class StringParser {

    /**
     * Serializes a string {@link Map} to <b>php's</b> equivalent
     * <code>serialize()</code> function.
     *
     * @param value     The {@link Map} to be serialized
     * @return          The serialized String.
     */
    public String serialize(Map<String, String> value) {
        StringBuilder serializedString = new StringBuilder();

        serializedString.append("a:").append(value.size()).append(":{");

        value.forEach((key, val) -> {
            // Escape urls
            String valEscaped = URLDecoder.decode(val, StandardCharsets.UTF_8);

            serializedString.append(generateInnerValues(key));
            serializedString.append(generateInnerValues(valEscaped));
        });

        serializedString.append("}");

        return serializedString.toString();
    }


    /**
     * Generates the inner values for serialization
     */
    private String generateInnerValues(String val) {
        return String.format("s:%d:\"%s\";", val.length(), val);
    }
}
`

In the generateInnerValues, it is taking length of the value but instead it should take length of bytes of value. Webhook gets failed when customer's name has a special character in it. I have seen that in your github repository this code is updated but the dependency I've been getting from mavem, it has this mistake

**Comment by jamius19** [comment]
@sameerjfreaks Thanks for the detailed info despite my (very) late reply.
Yeah, it's fixed now thanks to @MarcoSpoerl 

Closing the issue. I'll be updating the dependency shortly. Thanks!
